seed_everything: 42
trainer:
  logger:
    class_path: TensorBoardLogger
    init_args:
      save_dir: .
      name: logs
      default_hp_metric: False
  callbacks:
    - class_path: XLabRichModelSummary
      init_args:
        max_depth: 5
    - XLabRichProgressBar
    - LearningRateMonitor
    - class_path: ModelCheckpoint
      init_args:
        monitor: val_loss
        save_last: true
        save_top_k: 10
        mode: min
#    - class_path: EarlyStopping
#      init_args:
#        monitor: val_loss
#        min_delta: 0
#        patience: 5
#        mode: min
  max_epochs: 20
  enable_model_summary: false  # prevents a warning that the callback is already configured
  deterministic: true
optimizer:
  class_path: Adam
  init_args:
    lr: 3e-4
    weight_decay: 0
