seed_everything: 42
trainer:
  precision: null  # 32 / 16-mixed
  logger:
    class_path: TensorBoardLogger
    init_args:
      save_dir: .
  callbacks:
    - XLabRichProgressBar
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: ModelCheckpoint
      init_args:
        monitor: val_loss
        mode: min
        save_last: true
        save_top_k: 10
    - class_path: EarlyStopping
      init_args:
        monitor: val_loss
        mode: min
        patience: 5
  max_epochs: 20
  deterministic: true
  benchmark: false
model:
  max_len: 128
  d_model: 256
  position: xlab.transformers.PositionalEncoding
  n_blocks: 4
  n_heads: 4
  d_ff: 512
  dropout: 0.1
  prenorm: false
  postnorm: false
  norm: torch.nn.LayerNorm
  activation: torch.nn.ReLU
  attn_drop: true
  ff_drop: true
data:
  path: wikipedia
  name: 20220301.simple
  splits:
    train: 0.1
    val: 0.05
    test: 0.05
    predict: 0.05
  tokenizer: basic_english
  language: en
  max_tokens: 20_000
  column: text
  num_proc: 4
  progress: tqdm
  batch_size: 64
  pin_memory: false
  num_workers: 4
  persistent_workers: false
optimizer:
  class_path: Adam
  init_args:
    lr: 3e-4
    weight_decay: 0.0
lr_scheduler:
  class_path: ReduceLROnPlateau
  init_args:
    monitor: val_loss
    mode: min
    factor: 0.1
    patience: 2
    min_lr: 1e-5
