data:
  bulk_options:
    split:
      writer_batch_size: 1000
    encode:
      batch_size: 1000
      num_proc: 4
    index:
      batch_size: 1000
      n_jobs: 4
      threaded: true
    tokenizer_train_load:
      batch_size: 1000
      n_jobs: 4
      threaded: false
